# 1.With out using pipeline 

In [1]:
import numpy as np 
import pandas as pd 

In [2]:
tdf = pd.read_csv(r"C:\Users\HP\Desktop\data\titani1.csv")

In [3]:
tdf.sample(2)

PassengerId  Survived  Pclass                                   Name  \
246          247         0       3  Lindahl, Miss. Agda Thorilda Viktoria   
196          197         0       3                    Mernagh, Mr. Robert   

        Sex   Age  SibSp  Parch  Ticket   Fare Cabin Embarked  
246  female  25.0      0      0  347071  7.775   NaN        S  
196    male   NaN      0      0  368703  7.750   NaN        Q

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [5]:
tdf.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [6]:
tdf.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [7]:
# strp 1 -> train/test/split
x_train,x_test,y_train,y_test = train_test_split(tdf.drop(columns=['Survived']),
                                                tdf['Survived'],
                                                test_size=0.2,
                                                random_state=42)

In [8]:
x_train.head(3)

Pclass   Sex   Age  SibSp  Parch    Fare Embarked
331       1  male  45.5      0      0  28.500        S
733       2  male  23.0      0      0  13.000        S
382       3  male  32.0      0      0   7.925        S

In [9]:
y_train

331    0
733    0
382    0
704    0
813    0
      ..
106    1
270    0
860    0
435    1
102    0
Name: Survived, Length: 712, dtype: int64

In [10]:
tdf.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

### applying imputer to fill the missing value

In [11]:
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.fit_transform(x_test[['Age']])
x_test_embarked = si_embarked.fit_transform(x_test[['Embarked']])


In [20]:
#x_train_age

In [19]:
#x_test_embarked

### Onehotencoding

In [12]:
ohe_Sex = OneHotEncoder(sparse=False,handle_unknown = 'ignore')
ohe_Embarked = OneHotEncoder(sparse=False,handle_unknown = 'ignore')

x_train_sex = ohe_Sex.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_Embarked.fit_transform(x_train_embarked)

x_test_sex = ohe_Sex.fit_transform(x_test[['Sex']])
x_test_embarked = ohe_Embarked.fit_transform(x_test_embarked)

In [14]:
# x_test_embarked

In [15]:
x_train_rem = x_train.drop(columns=['Sex','Age','Embarked'])

In [16]:
x_test_rem = x_test.drop(columns=['Sex','Age','Embarked'])

In [17]:
x_train_transfromed = np.concatenate((x_train_rem,x_train_age,x_train_sex,x_train_embarked),axis = 1)
x_test_transfromed = np.concatenate((x_test_rem,x_test_age,x_test_sex,x_test_embarked),axis = 1)

In [19]:
x_train_transfromed

array([[1., 0., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 2., 0., ..., 0., 0., 1.],
       [1., 1., 2., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.]])

In [20]:
x_train_transfromed.shape

(712, 10)

In [21]:
x_test_transfromed

array([[3., 1., 1., ..., 1., 0., 0.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       ...,
       [3., 1., 5., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 0., 1.],
       [3., 1., 1., ..., 0., 0., 1.]])

In [22]:
x_test_transfromed.shape

(179, 10)

In [18]:
clf = DecisionTreeClassifier()
clf.fit(x_train_transfromed,y_train)

DecisionTreeClassifier()

In [23]:
y_pred = clf.predict(x_test_transfromed)

In [25]:
y_pred

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7430167597765364

In [28]:
import pickle