In [12]:
import numpy as np
a=np.array(4)
print(a)

4


In [14]:
type(a)

numpy.ndarray

In [15]:
a.ndim

0

In [16]:
import numpy as np
b=np.array([4,2,
            3,4,5,6,7,8,9])
print(b)

[4 2 3 4 5 6 7 8 9]


In [17]:
b.ndim

1

In [18]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
mat.ndim

2

In [2]:
class Classy(object):
    def __init__(self): 
        self.items = []
        self.classiness = 0

    def getClassiness(self):
        print(self.classiness)

    def createList(self):
        self.items.append(item)

    def addItem(self, item):

        if item=="tophat":
            self.classiness+=2
        elif item=="bowtie":
            self.classiness+=4
        elif item=="monocle":
            self.classiness+=5
        else:
            self.classiness+=0

        return self.classiness

# Test cases
me = Classy()

# Should be 0
print (me.getClassiness())

me.addItem("tophat")
# Should be 2
print (me.getClassiness())

me.addItem("bowtie")
me.addItem("jacket")
me.addItem("monocle")
# Should be 11
print (me.getClassiness())

me.addItem("bowtie")
# Should be 15
print (me.getClassiness())

0
None
2
None
11
None
15
None
